export const QUEUE_NAMES = {
  TRANSLATE_QUEUE: 'translate-queue', 
  DATABASE_QUEUE:"database-queue"
 };


 export const JOB_NAMES = {
  CRATE_NEW_USER_TABLE:"auth_job",
  ADD_USER_LIBRARY_REPLANISH : "ADD_USER_LIBRARY_REPLANISH",
   DICTIONARY_REPLANISH: "DICTIONARY_REPLANISH",
   REMOVE_FROM_DICTONARY:"REMOVE_FROM_DICTONARY",
   UPDATE_DICTIONARY_PROGRESS:"UPDATE_DICTIONARY_PROGRESS",
   UPDATE_LEARNED_STATUS:"UPDATE_LEARNED_STATUS",
REMOVE_TEXT:"REMOVE_TEXT",
RENAME_TEXT:"RENAME_TEXT",
  TRANSLATE: 'translate_job', 
 };
